run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - paramTypeCombine  # Allow multiple string parameters
      - hugeParam         # Allow large structs as parameters (Terraform framework requirement)
  
  gocyclo:
    min-complexity: 15
  
  godot:
    scope: declarations
    capital: false
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/halradaideh/terraform-provider-puppetca
  
  revive:
    min-confidence: 0.8
    rules:
      - name: exported
        disabled: true  # Allow unexported public functions for internal packages
  
  mnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
          - assign
        ignored-numbers:
          - "2"
          - "20"
  
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Allow struct field alignment issues for readability
  
  lll:
    line-length: 160  # Increase line length for Terraform provider patterns
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  funlen:
    lines: 80  # Increase function length limit for Terraform CRUD operations
    statements: 50
  
  depguard:
    rules:
      main:
        allow:
          - $all
  
  unused:
    check-exported: false
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  
  disable:
    - gochecknoinits # Allow init functions for provider registration
    - copyloopvar    # Requires Go 1.22+

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-dirs:
    - vendor
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
    
    # Exclude known linter issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    
    # Exclude shadow checking for err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - predeclared
    
    # Exclude lll issues for long lines in comments
    - source: "^//.*"
      linters:
        - lll
    
    # Allow missing package comments for internal packages
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
      path: "internal/"
    
    # Allow missing comments for exported functions in internal packages
    - text: "exported (function|method|type|var) .* should have comment or be unexported"
      linters:
        - revive
      path: "internal/"
    
    # Allow struct field naming for Terraform schema compatibility
    - text: "struct field `?Url`? should be `?URL`?"
      linters:
        - stylecheck
        - revive
    
    # Allow magic numbers for timeouts and common values
    - text: "Magic number: 20, in <argument> detected"
      linters:
        - mnd
    - text: "Magic number: 2, in <condition> detected"
      linters:
        - mnd
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false 