name: Bug Report
description: File a bug report to help us improve the provider
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - halradaideh

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: provider-version
    attributes:
      label: Provider Version
      description: What version of the Terraform Puppet CA provider are you using?
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: What version of Terraform are you using?
      placeholder: "1.6.0"
    validations:
      required: true

  - type: input
    id: puppet-version
    attributes:
      label: Puppet CA Version
      description: What version of Puppet CA are you using?
      placeholder: "7.x"
    validations:
      required: false

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you running Terraform on?
      options:
        - Linux
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows
        - FreeBSD
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: terraform-config
    attributes:
      label: Terraform Configuration
      description: Please provide the relevant Terraform configuration that reproduces the issue.
      render: hcl
      placeholder: |
        resource "puppetca_certificate" "example" {
          name = "example-node"
          # ... rest of configuration
        }
    validations:
      required: true

  - type: textarea
    id: terraform-output
    attributes:
      label: Terraform Output
      description: Please provide the output from Terraform (with sensitive information redacted).
      render: shell
      placeholder: |
        $ terraform apply
        # Paste the output here
    validations:
      required: false

  - type: textarea
    id: debug-logs
    attributes:
      label: Debug Logs
      description: |
        If applicable, please provide debug logs. You can enable debug logging with:
        `export TF_LOG=DEBUG` and `export TF_LOG_PATH=terraform.log`
      render: text
      placeholder: Paste debug logs here (redact sensitive information)
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure provider with...
        2. Run terraform apply...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true 